<a href="https://colab.research.google.com/github/ronniedejose/Finallinear/blob/main/Ronnie_De_Jose_Assign_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear Algebra Lab Activity 4**

Matrices which is the plural word of Matrix, which also refers to a rectangular array of numbers matrices is also compact which enables it to write and work with multiple linear equations, or system of linear equation






# **Lab Activity Objectives**
At the end of this activity you will be able to:

1.   Be familiar with matrices and their relation to linear equations.
2.   Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.




In [63]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

#**Task 1**
Create a function named `desc_mat()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [25]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

## **Matrix**

In [4]:
null_mat = np.array([])


In [5]:
zero_mat_sqr = np.zeros((3,3))

In [15]:
ones_mat_sqr = np.ones((3,3))

In [18]:
A = np.array([
    [3, 0, 0],
    [0, 3, 0],
    [0, 0, 9]
])

In [19]:
B = np.array([
    [1, 8, 1],
    [0, 4, 7],
    [0, 0, 9]
])

In [33]:
C = np.array([
    [2, 0, 0],
    [6, 4, 0],
    [7, 7, 1]
])

## **Testing**

### **Null Matrix**

In [64]:
describe_mat(null_mat)

Matrix:
[]

Shape:	(0,)
Rank:	1



### **Zero Matrix**

In [27]:
describe_mat(zero_mat_sqr)

Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape:	(3, 3)
Rank:	2



### **Ones Matrix**

In [28]:
describe_mat(ones_mat_sqr)

Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Shape:	(3, 3)
Rank:	2



### **Diagonal Matrix**

In [29]:
describe_mat(A)

Matrix:
[[3 0 0]
 [0 3 0]
 [0 0 9]]

Shape:	(3, 3)
Rank:	2



### **Identity Matrix**

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **Upper Triangular **

In [31]:
describe_mat(B)

Matrix:
[[1 8 1]
 [0 4 7]
 [0 0 9]]

Shape:	(3, 3)
Rank:	2



### **Lower Triangular Matrix**

In [32]:
describe_mat(C)

Matrix:
[[2 0 0]
 [6 4 0]
 [7 7 1]]

Shape:	(3, 3)
Rank:	2



# **Task Number 2**
Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [46]:
def operations(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

## **Matrix** 

### **Addition**

In [38]:
a = np.array([
    [3,1,9],
    [2,0,7],
    [7,1,7]
])
b = np.array([
    [3,2,3],
    [0,4,0],
    [1,1,1]
])

### **Subtraction**

In [39]:
c = np.array([
    [4,1,1],
    [3,5,5],
    [0,7,0]
])
d = np.array([
    [9,2,6],
    [9,1,0],
    [0,0,6]
])

### **Multiplication**

In [56]:
e = np.array([
    [2,2,2],
    [4,3,4],
    [5,7,7]
])
f = np.array([
    [3,3,3],
    [0,1,9],
    [0,0,6]
])

### **Division**

In [41]:
g = np.array([
    [10,12,21],
    [15,9,0],
    [20,22,11]
])
h = np.array([
    [2,6,7],
    [5,3,1],
    [10,11,1]
])

## Testing

### **Addition**

In [52]:
TT = a+b
operations(TT)
np.add(a,b)

Matrix:
[[ 6  3 12]
 [ 2  4  7]
 [ 8  2  8]]

Shape:	(3, 3)
Rank:	2



array([[ 6,  3, 12],
       [ 2,  4,  7],
       [ 8,  2,  8]])

### **Subtraction**

In [54]:
TT = c-d
operations(TT)
np.subtract(c,d)

Matrix:
[[-5 -1 -5]
 [-6  4  5]
 [ 0  7 -6]]

Shape:	(3, 3)
Rank:	2



array([[-5, -1, -5],
       [-6,  4,  5],
       [ 0,  7, -6]])

### **Multiplication**

In [60]:
2*e
TT = e*f
operations(TT)
np.multiply(e,f)
4*f

Matrix:
[[ 6  6  6]
 [ 0  3 36]
 [ 0  0 42]]

Shape:	(3, 3)
Rank:	2



array([[12, 12, 12],
       [ 0,  4, 36],
       [ 0,  0, 24]])

### **Division**

In [62]:
TT = g/h
operations(TT)
np.divide(g,h)
g/5
1/h

Matrix:
[[ 5.  2.  3.]
 [ 3.  3.  0.]
 [ 2.  2. 11.]]

Shape:	(3, 3)
Rank:	2



array([[0.5       , 0.16666667, 0.14285714],
       [0.2       , 0.33333333, 1.        ],
       [0.1       , 0.09090909, 1.        ]])

# **Conclusion**


Based on the Lab work done by the students it signifies that having a fundamental information about matrix is most likely a benefit for the student due to the reason that the students possibly already know what codes to input and distinguish what are the necessary codes needed for that specific program to be inputed. Likewise, Matrix operation do help in taking care of issues in innovation as far as security as it play a significant role in detection of a problem, in science for refraction and reflection, and also in mathematics 