<a href="https://colab.research.google.com/github/ronniedejose/Finallinear/blob/main/Ronnie_De_Jose_Assign_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear Algebra Lab Activity 4**

Matrices which is the plural word of Matrix, which also refers to a rectangular array of numbers matrices is also compact which enables it to write and work with multiple linear equations, or system of linear equation






# **Lab Activity Objectives**
At the end of this activity you will be able to:

1.   Be familiar with matrices and their relation to linear equations.
2.   Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.




In [63]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

# **Row and Column Matrices**

In [69]:
def pogiko(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [70]:
a = np.array([
    [1,1],
    [2,2]
])
pogiko (a)

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [71]:
# Declaring a 3 x 2 matrix
b = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
pogiko(b)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [72]:
c = np.array([1,2,3,4,5])
pogiko(c)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



In [75]:
# Declaring a Rox matrix

pogiko1 = np.array([
    1, 3, 2
]) 
# this 1-D Matrix, a shape of (3,), not  considered a row matrix.
pogiko2 = np.array([
    [1,2,3]                
]) 
# this2-D Matrix with a shape of (1,3)
pogiko(pogiko1)
pogiko(pogiko2)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [76]:
# Declaring a Col Matrix

pogiko1 = np.array([
    [1],
    [2],
    [5]
]) 
# a 2-D Matrix with a shape of (3,1)
pogiko(pogiko1)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



# **Square Matrices**

In [79]:
def labyusir(matrix):
    lemonsquare = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {lemonsquare}\n')

In [80]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
labyusir(square_mat)
labyusir(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



# **Null Matrix**

In [82]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [83]:
# Testing for null
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


# **Zero Matrix**

In [84]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]



# **Ones Matrix**

In [85]:

ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]



# **Diagonal Matrix**

In [86]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

# **Identity Matrix**

In [87]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# **Upper Triangular Matrix**

In [89]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])


array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])

# **Lower Triangular Matrix**

In [90]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

# **Practice**
1. Given the linear combination below, try to create a corresponding matrix representing it.
$$θ = 5x + 3y - z$$
$$
θ=\begin{bmatrix} 5 &amp; 3 &amp; -1\end{bmatrix}
$$
2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.
$$ A = \left\{\begin{array} 5x_1 + 2x_2 +x_3\\ 4x_2 - x_3\\ 10x_3 \end{array}\right. $$
\$$
A=\begin{bmatrix} 1 &amp; 2 &amp; 1 \\ 0 &amp; 4 &amp; -1 \\ 0 &amp; 0 &amp; 10\end{bmatrix}
$$\ The matrix is upper triangle matrix because of the 3 zeros on the lower left part of the matrix.

1. Given the matrix below, express it as a linear combination in a markdown.

In [91]:
a = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])
describe_mat(a)

Matrix:
[[1 7 8]
 [2 2 2]
 [4 6 7]]

Shape:	(3, 3)
Rank:	2
Is Square: True



1. Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [92]:
H = np.tril(G)
H

array([[1, 0],
       [2, 2]])

$$ G = \left\{ \begin{array}\ x+7y+8z \\ 2x +2y -2z \\ 4x + 6y +7z \end{array} \right. $$


Given the matrix below, display the output as a LaTex

In [93]:
H = np.triu(G)
H

array([[1, 1],
       [0, 2]])

# **Matrix Algebra**

## **Addition**

In [94]:
a = np.array([
    [1,2],
    [2,3],
    [4,1]
])
b = np.array([
    [2,2],
    [0,0],
    [1,1]
])
a+b

array([[3, 4],
       [2, 3],
       [5, 2]])

In [95]:
2+A

array([[3, 4],
       [5, 3]])

## **Subtraction**

In [96]:
a-b

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [98]:
3-b == 3*np.ones(b.shape)-b

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## **Multiplication**

In [99]:
a*b
np.multiply(a,b)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [100]:
2*a

array([[2, 4],
       [4, 6],
       [8, 2]])

In [103]:
TT = a/b
operations(TT)
np.divide(a,b)

Matrix:
[[0.5 1. ]
 [inf inf]
 [4.  1. ]]

Shape:	(3, 2)
Rank:	2



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([[0.5, 1. ],
       [inf, inf],
       [4. , 1. ]])

In [105]:
alpha=10**-10
a/(alpha+b)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [106]:
np.add(a,b)

array([[3, 4],
       [2, 3],
       [5, 2]])

#**Task 1**
Create a function named `desc_mat()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [25]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [65]:
# Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)


Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



## **Matrix**

In [4]:
null_mat = np.array([])


In [5]:
zero_mat_sqr = np.zeros((3,3))

In [15]:
ones_mat_sqr = np.ones((3,3))

In [107]:
A = np.array([
    [3, 0, 0],
    [0, 3, 0],
    [0, 0, 9]
])

In [19]:
B = np.array([
    [1, 8, 1],
    [0, 4, 7],
    [0, 0, 9]
])

In [33]:
C = np.array([
    [2, 0, 0],
    [6, 4, 0],
    [7, 7, 1]
])

## **Testing**

### **Null Matrix**

In [64]:
describe_mat(null_mat)

Matrix:
[]

Shape:	(0,)
Rank:	1



### **Zero Matrix**

In [27]:
describe_mat(zero_mat_sqr)

Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape:	(3, 3)
Rank:	2



### **Ones Matrix**

In [28]:
describe_mat(ones_mat_sqr)

Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Shape:	(3, 3)
Rank:	2



### **Diagonal Matrix**

In [29]:
describe_mat(A)

Matrix:
[[3 0 0]
 [0 3 0]
 [0 0 9]]

Shape:	(3, 3)
Rank:	2



### **Identity Matrix**

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **Upper Triangular **

In [31]:
describe_mat(B)

Matrix:
[[1 8 1]
 [0 4 7]
 [0 0 9]]

Shape:	(3, 3)
Rank:	2



### **Lower Triangular Matrix**

In [32]:
describe_mat(C)

Matrix:
[[2 0 0]
 [6 4 0]
 [7 7 1]]

Shape:	(3, 3)
Rank:	2



# **Task Number 2**
Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [46]:
def operations(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

## **Matrix** 

### **Addition**

In [108]:
a = np.array([
    [3,1,9],
    [2,0,7],
    [7,1,7]
])
b = np.array([
    [3,2,3],
    [0,4,0],
    [1,1,1]
])

### **Subtraction**

In [39]:
c = np.array([
    [4,1,1],
    [3,5,5],
    [0,7,0]
])
d = np.array([
    [9,2,6],
    [9,1,0],
    [0,0,6]
])

### **Multiplication**

In [56]:
e = np.array([
    [2,2,2],
    [4,3,4],
    [5,7,7]
])
f = np.array([
    [3,3,3],
    [0,1,9],
    [0,0,6]
])

### **Division**

In [41]:
g = np.array([
    [10,12,21],
    [15,9,0],
    [20,22,11]
])
h = np.array([
    [2,6,7],
    [5,3,1],
    [10,11,1]
])

## Testing

### **Addition**

In [52]:
TT = a+b
operations(TT)
np.add(a,b)

Matrix:
[[ 6  3 12]
 [ 2  4  7]
 [ 8  2  8]]

Shape:	(3, 3)
Rank:	2



array([[ 6,  3, 12],
       [ 2,  4,  7],
       [ 8,  2,  8]])

### **Subtraction**

In [54]:
TT = c-d
operations(TT)
np.subtract(c,d)

Matrix:
[[-5 -1 -5]
 [-6  4  5]
 [ 0  7 -6]]

Shape:	(3, 3)
Rank:	2



array([[-5, -1, -5],
       [-6,  4,  5],
       [ 0,  7, -6]])

### **Multiplication**

In [60]:
2*e
TT = e*f
operations(TT)
np.multiply(e,f)
4*f

Matrix:
[[ 6  6  6]
 [ 0  3 36]
 [ 0  0 42]]

Shape:	(3, 3)
Rank:	2



array([[12, 12, 12],
       [ 0,  4, 36],
       [ 0,  0, 24]])

### **Division**

In [62]:
TT = g/h
operations(TT)
np.divide(g,h)
g/5
1/h

Matrix:
[[ 5.  2.  3.]
 [ 3.  3.  0.]
 [ 2.  2. 11.]]

Shape:	(3, 3)
Rank:	2



array([[0.5       , 0.16666667, 0.14285714],
       [0.2       , 0.33333333, 1.        ],
       [0.1       , 0.09090909, 1.        ]])

# **Conclusion**


Based on the Lab work done by the students it signifies that having a fundamental information about matrix is most likely a benefit for the student due to the reason that the students possibly already know what codes to input and distinguish what are the necessary codes needed for that specific program to be inputed. Likewise, Matrix operation do help in taking care of issues in innovation as far as security as it play a significant role in detection of a problem, in science for refraction and reflection, and also in mathematics 

# **Reference**



*   https://byjus.com/jee/types-of-matrices/
*   https://machinelearningmastery.com/introduction-to-types-of-matrices-in-linear-algebra/
*   https://www.embibe.com/exams/where-are-matrices-used-in-daily-life/